<?php

session_start();

include_once 'vendor/sonata-project/google-authenticator/src/FixedBitNotation.php';
include_once 'vendor/sonata-project/google-authenticator/src/GoogleAuthenticatorInterface.php';
include_once 'vendor/sonata-project/google-authenticator/src/GoogleAuthenticator.php';
include_once 'vendor/sonata-project/google-authenticator/src/GoogleQrUrl.php';
include_once 'model/user.php';

$user = new User();
$g = new \Google\Authenticator\GoogleAuthenticator();
$secret = $_POST['secret_key'];
$code = $_POST['code']; //6-digit code generated by Google Authenticator app
$username = $_POST['username'];

if ($g->checkCode($secret, $code)) {
    echo "<script>alert('Authorized!')</script>";
    $user->enable2FA($username, $secret);
} else {
    echo "<script>alert('Incorrect or expired code!')</script>";
    echo "<script>history.back()</script>";
}
